### ISSUE TITLE
concurrent map read and map write

### ISSUE THREAD

**Issue by subandroid** [segmentio/analytics-go#120] opened 2018-01-05 23:38 UTC
Our application is crashing due to this: 

```
fatal error: concurrent map read and map write

goroutine 3842146 [running]:
runtime.throw(0xdf3043, 0x21)
#011/usr/local/go/src/runtime/panic.go:596 +0x95 fp=0xc4260ed380 sp=0xc4260ed360
runtime.mapaccess2(0xd27ae0, 0xc4203da1e0, 0xc429796be8, 0x7c43cc, 0xc426633970)
#011/usr/local/go/src/runtime/hashmap.go:377 +0x244 fp=0xc4260ed3c8 sp=0xc4260ed380
reflect.mapaccess(0xd27ae0, 0xc4203da1e0, 0xc429796be8, 0xc4203da1e0)
#011/usr/local/go/src/runtime/hashmap.go:1128 +0x3f fp=0xc4260ed400 sp=0xc4260ed3c8
reflect.Value.MapIndex(0xd27ae0, 0xc4203da1e0, 0x15, 0xcf6f20, 0xc429796be8, 0x86, 0xcf6e60, 0xc42d7a8188, 0x82)
#011/usr/local/go/src/reflect/value.go:1058 +0x128 fp=0xc4260ed488 sp=0xc4260ed400
encoding/json.(*mapEncoder).encode(0xc42000e4c8, 0xc426633970, 0xd27ae0, 0xc4203da1e0, 0x15, 0xd20100)
#011/usr/local/go/src/encoding/json/encode.go:690 +0x534 fp=0xc4260ed5f8 sp=0xc4260ed488
encoding/json.(*mapEncoder).(encoding/json.encode)-fm(0xc426633970, 0xd27ae0, 0xc4203da1e0, 0x15, 0xc4203d0100)
#011/usr/local/go/src/encoding/json/encode.go:706 +0x64 fp=0xc4260ed638 sp=0xc4260ed5f8
encoding/json.(*encodeState).reflectValue(0xc426633970, 0xd27ae0, 0xc4203da1e0, 0x15, 0xc4203d0100)
#011/usr/local/go/src/encoding/json/encode.go:323 +0x82 fp=0xc4260ed670 sp=0xc4260ed638
encoding/json.interfaceEncoder(0xc426633970, 0xd1a1a0, 0xc420e8c820, 0x94, 0xc420e80100)
#011/usr/local/go/src/encoding/json/encode.go:617 +0xdb fp=0xc4260ed6b0 sp=0xc4260ed670
encoding/json.(*mapEncoder).encode(0xc42000e3d0, 0xc426633970, 0xd2a420, 0xc422ad1600, 0x195, 0x100)
#011/usr/local/go/src/encoding/json/encode.go:690 +0x589 fp=0xc4260ed820 sp=0xc4260ed6b0
encoding/json.(*mapEncoder).(encoding/json.encode)-fm(0xc426633970, 0xd2a420, 0xc422ad1600, 0x195, 0x100)
#011/usr/local/go/src/encoding/json/encode.go:706 +0x64 fp=0xc4260ed860 sp=0xc4260ed820
encoding/json.(*structEncoder).encode(0xc42054e540, 0xc426633970, 0xd99980, 0xc422ad15f0, 0x199, 0xc426630100)
#011/usr/local/go/src/encoding/json/encode.go:645 +0x253 fp=0xc4260ed9c0 sp=0xc4260ed860
encoding/json.(*structEncoder).(encoding/json.encode)-fm(0xc426633970, 0xd99980, 0xc422ad15f0, 0x199, 0xc422ad0100)
#011/usr/local/go/src/encoding/json/encode.go:659 +0x64 fp=0xc4260eda00 sp=0xc4260ed9c0
encoding/json.(*ptrEncoder).encode(0xc42000e4a0, 0xc426633970, 0xd32520, 0xc422ad15f0, 0x16, 0xd30100)
#011/usr/local/go/src/encoding/json/encode.go:786 +0xe3 fp=0xc4260eda40 sp=0xc4260eda00
encoding/json.(*ptrEncoder).(encoding/json.encode)-fm(0xc426633970, 0xd32520, 0xc422ad15f0, 0x16, 0xc422ad0100)
#011/usr/local/go/src/encoding/json/encode.go:791 +0x64 fp=0xc4260eda80 sp=0xc4260eda40
encoding/json.(*encodeState).reflectValue(0xc426633970, 0xd32520, 0xc422ad15f0, 0x16, 0xc422ad0100)
#011/usr/local/go/src/encoding/json/encode.go:323 +0x82 fp=0xc4260edab8 sp=0xc4260eda80
encoding/json.interfaceEncoder(0xc426633970, 0xd1a1a0, 0xc427424000, 0x194, 0xd10100)
#011/usr/local/go/src/encoding/json/encode.go:617 +0xdb fp=0xc4260edaf8 sp=0xc4260edab8
encoding/json.(*arrayEncoder).encode(0xc42000e3e8, 0xc426633970, 0xcec820, 0xc4204019e8, 0x197, 0x100)
#011/usr/local/go/src/encoding/json/encode.go:767 +0xf5 fp=0xc4260edb50 sp=0xc4260edaf8
encoding/json.(*arrayEncoder).(encoding/json.encode)-fm(0xc426633970, 0xcec820, 0xc4204019e8, 0x197, 0x100)
#011/usr/local/go/src/encoding/json/encode.go:774 +0x64 fp=0xc4260edb90 sp=0xc4260edb50
encoding/json.(*sliceEncoder).encode(0xc42000e3f0, 0xc426633970, 0xcec820, 0xc4204019e8, 0x197, 0x100)
#011/usr/local/go/src/encoding/json/encode.go:741 +0xc1 fp=0xc4260edbd0 sp=0xc4260edb90
encoding/json.(*sliceEncoder).(encoding/json.encode)-fm(0xc426633970, 0xcec820, 0xc4204019e8, 0x197, 0x100)
#011/usr/local/go/src/encoding/json/encode.go:753 +0x64 fp=0xc4260edc10 sp=0xc4260edbd0
encoding/json.(*structEncoder).encode(0xc42054e150, 0xc426633970, 0xd6bd60, 0xc4204019e0, 0x199, 0x100)
#011/usr/local/go/src/encoding/json/encode.go:645 +0x253 fp=0xc4260edd70 sp=0xc4260edc10
encoding/json.(*structEncoder).(encoding/json.encode)-fm(0xc426633970, 0xd6bd60, 0xc4204019e0, 0x199, 0xc420400100)
#011/usr/local/go/src/encoding/json/encode.go:659 +0x64 fp=0xc4260eddb0 sp=0xc4260edd70
encoding/json.(*ptrEncoder).encode(0xc42000e418, 0xc426633970, 0xd322a0, 0xc4204019e0, 0x16, 0xd30100)
#011/usr/local/go/src/encoding/json/encode.go:786 +0xe3 fp=0xc4260eddf0 sp=0xc4260eddb0
encoding/json.(*ptrEncoder).(encoding/json.encode)-fm(0xc426633970, 0xd322a0, 0xc4204019e0, 0x16, 0xc420400100)
#011/usr/local/go/src/encoding/json/encode.go:791 +0x64 fp=0xc4260ede30 sp=0xc4260eddf0
encoding/json.(*encodeState).reflectValue(0xc426633970, 0xd322a0, 0xc4204019e0, 0x16, 0x100)
#011/usr/local/go/src/encoding/json/encode.go:323 +0x82 fp=0xc4260ede68 sp=0xc4260ede30
encoding/json.(*encodeState).marshal(0xc426633970, 0xd322a0, 0xc4204019e0, 0xc40d2b0100, 0x0, 0x0)
#011/usr/local/go/src/encoding/json/encode.go:296 +0xb8 fp=0xc4260edea0 sp=0xc4260ede68
encoding/json.Marshal(0xd322a0, 0xc4204019e0, 0x132e220, 0xc4283865a0, 0x18, 0xe0e668, 0x0)
#011/usr/local/go/src/encoding/json/encode.go:161 +0x6e fp=0xc4260edee8 sp=0xc4260edea0
github.com/ory/hydra/vendor/github.com/segmentio/analytics-go.(*Client).send(0xc420080200, 0xc427424000, 0x2, 0xfa, 0x0, 0x720658)
#011/bamboo/xml-data/build-dir/CLDREL-CSHYD2-JOB1/crowdstrike/cloud_build/cs-hydra/src/github.com/ory/hydra/vendor/github.com/segmentio/analytics-go/analytics.go:285 +0x155 fp=0xc4260edf78 sp=0xc4260edee8
github.com/ory/hydra/vendor/github.com/segmentio/analytics-go.(*Client).sendAsync.func1(0xc420080200, 0xc427424000, 0x2, 0xfa)
#011/bamboo/xml-data/build-dir/CLDREL-CSHYD2-JOB1/crowdstrike/cloud_build/cs-hydra/src/github.com/ory/hydra/vendor/github.com/segmentio/analytics-go/analytics.go:261 +0x4d fp=0xc4260edfc0 sp=0xc4260edf78
runtime.goexit()
#011/usr/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc4260edfc8 sp=0xc4260edfc0
created by github.com/ory/hydra/vendor/github.com/segmentio/analytics-go.(*Client).sendAsync
#011/bamboo/xml-data/build-dir/CLDREL-CSHYD2-JOB1/crowdstrike/cloud_build/cs-hydra/src/github.com/ory/hydra/vendor/github.com/segmentio/analytics-go/analytics.go:270 +0xed
```

we are using go 1.8.3 on trusty ubuntu. I'm still investigating the exact cause of this but it may have to do with the gobal DefaultContext variable in analytics.go. Not quite sure where things are going wrong yet, i.e. how it is read/write-ing at the same time.

```
// DefaultContext of message batches.
var DefaultContext = map[string]interface{}{
	"library": map[string]interface{}{
		"name":    "analytics-go",
		"version": Version,
	},
}
```
which is assigned to
```
batch.Context
```
at https://github.com/segmentio/analytics-go/blob/bdb0aeca8a993b292b85c9ec17b5ce0ff81848c8/analytics.go#L283

**Comment by f2prateek** [comment] 2018-01-05 23:41
hey @subandroid, thanks for the report. I have a few more details to ask here:

* Which version of the `analytics-go` library are you using?
* Are you modifying the `DefaultContext` variable?
* Do you have a small reproducible sample we can test with?

**Comment by subandroid** [comment] 2018-01-05 23:44
thanks for the prompt respond, from the History.md I believe it is v2.1.1

**Comment by f2prateek** [comment] 2018-01-05 23:48
Got it, I don't see anything obvious in v2.1.1 that could be causing the issue. We don't ever mutate the `DefaultContext` variable ourselves. My current best guess is that something in your application is mutating the `DefaultContext` variable (either by deleting, adding or replacing some keys).

**Comment by subandroid** [comment] 2018-01-05 23:50
Possible. I'll keep looking.

**Comment by subandroid** [comment] 2018-01-05 23:54
Did a global search in hydra's code and nothing seems to access DefaultContext.

**Comment by f2prateek** [comment] 2018-01-06 00:02
@subandroid that's too bad. Two things I'd suggest to debug this further:

1. Are you vendoring the dependency? If so, you could rename the DefaultContext variable to `defaultContext` to make it private (this would require a change here https://github.com/segmentio/analytics-go/blob/v2.0/analytics.go#L19 and here https://github.com/segmentio/analytics-go/blob/v2.0/analytics.go#L227), this would easily isolate the issue to instrumentation errors or library bugs.

2. If you can reproduce the issue reliably in your app but aren't to break into a small sample that can be shared, could you run your program with the race detector (`go run -race ...` as per https://blog.golang.org/race-detector)? This should help identify exactly where the read and writes are coming from.

**Comment by subandroid** [comment] 2018-01-06 00:09
Done #1. The problem is this is non-deterministic, so I can't yet reliably reproduce but I will keep trying.

**Comment by f2prateek** [comment] 2018-01-06 00:25
Thanks! I did a quick check on GitHub to see if it was maybe a 3rd party dependency that's possibly modifying the DefaultContext, but that doesn't seem to be case either (https://github.com/search?l=Go&q=analytics+DefaultContext&type=Code&utf8=%E2%9C%93 - most appear to be just vendored versions of analytics-go).

**Comment by f2prateek** [comment] 2018-01-06 00:36
I think you're right, I don't think `DefaultContext` is at fault here. Looking into Hydra, I wonder if any of these variables being passed as traits/properties are maps:

* https://github.com/ory/hydra/blob/dd1a3f47e4bb4224cd5eec2f72bad06b37b0f86b/metrics/middleware.go#L148-L158
* https://github.com/ory/hydra/blob/dd1a3f47e4bb4224cd5eec2f72bad06b37b0f86b/metrics/middleware.go#L95-L102

**Comment by f2prateek** [comment] 2018-01-06 00:39
Ahaa! Think I found it.

It looks like when it calls `track`, it passes a map as one of the properties https://github.com/ory/hydra/blob/dd1a3f47e4bb4224cd5eec2f72bad06b37b0f86b/metrics/middleware.go#L151.

This variable is defined here https://github.com/ory/hydra/blob/dd1a3f47e4bb4224cd5eec2f72bad06b37b0f86b/metrics/metrics.go#L200-L203. It is being updated here https://github.com/ory/hydra/blob/dd1a3f47e4bb4224cd5eec2f72bad06b37b0f86b/metrics/metrics.go#L200-L203.

As a fix, I'd recommend passing a copy to Segment instead. Something like `"paths":      copy(sw.Paths),`.

**Comment by f2prateek** [comment] 2018-01-06 00:59
Looks like a few other fields Hydra is tracking may also be affected. All these fields are being mutated after being passed to Segment.

* `methods`
* `status`
* `sizes`
* `latencies`

**Comment by subandroid** [comment] 2018-01-06 03:54
Sweet! Thanks @f2prateek, I will file an issue with hydra and get a PR going. Thank you for your for quick turnaround!

**Comment by f2prateek** [comment] 2018-01-08 19:33
@subandroid thanks! I'll close the issue here as there isn't any action for us to take at the moment. I'll discuss some options with the team to see if we should be better guarding against these kind of implementation mistakes.

**Closed** 2018-01-08 20:33 UTC
Labels: bug
